# Generated by Django 4.1.5 on 2023-01-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "Nebulosa"),
                    ("ESTRELA", "Estrela"),
                    ("GALAXIA", "Galáxia"),
                    ("PLANETA", "Planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
