# Generated by Django 4.1.5 on 2023-03-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galery", "0006_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
